QUESTION_BANK = {
"Science": {
"Beginner": [
{"q":"Which part of a plant usually absorbs water from the soil?","options":["Roots","Flowers","Fruit","Leaves"],"answer":"Roots","hint":"Think about the part hidden underground.","why":"Roots absorb water and minerals from the soil."},
{"q":"Which force pulls objects toward Earth?","options":["Gravity","Magnetism","Friction","Electricity"],"answer":"Gravity","hint":"It is the force that makes a dropped ball fall.","why":"Gravity attracts objects with mass toward one another, including toward Earth."},
{"q":"Water changing from liquid to gas is called what?","options":["Evaporation","Freezing","Condensation","Melting"],"answer":"Evaporation","hint":"Think about a puddle slowly disappearing on a warm day.","why":"Evaporation is the change of liquid water into water vapor."}] ,
"Intermediate":[
{"q":"Why does a metal spoon usually feel colder than a wooden spoon in the same room?","options":["Metal transfers heat away from your hand faster","Metal is always at a lower temperature","Wood creates heat","Metal contains cold energy"],"answer":"Metal transfers heat away from your hand faster","hint":"Both spoons may be the same temperature; think about heat transfer.","why":"Metal is a better thermal conductor than wood, so it draws heat from your hand faster."},
{"q":"Which organelle is often called the powerhouse of the cell?","options":["Mitochondrion","Nucleus","Ribosome","Cell wall"],"answer":"Mitochondrion","hint":"It helps cells release usable energy from food.","why":"Mitochondria help produce ATP, a main energy-carrying molecule in cells."},
{"q":"If a circuit is open, what usually happens to electric current?","options":["It stops flowing","It doubles","It becomes magnetic","It changes color"],"answer":"It stops flowing","hint":"Current needs a complete path.","why":"An open circuit breaks the conducting path, so current cannot flow around the loop."}],
"Advanced":[
{"q":"Why do astronauts appear weightless while orbiting Earth?","options":["They are continuously falling around Earth","There is no gravity in space","Their mass becomes zero","Air pressure lifts them"],"answer":"They are continuously falling around Earth","hint":"Gravity is still acting on the spacecraft.","why":"Orbit is continuous free fall: spacecraft and astronauts fall together around Earth."},
{"q":"Which statement best explains conservation of energy?","options":["Energy changes form but total energy is conserved in an isolated system","Energy disappears when friction occurs","Only moving objects contain energy","Energy can be created from nothing"],"answer":"Energy changes form but total energy is conserved in an isolated system","hint":"Think about energy transformations rather than disappearance.","why":"Energy can transform between forms, while total energy remains conserved in an isolated system."},
{"q":"In a food web, what is the most direct role of decomposers?","options":["Return nutrients from dead matter to the ecosystem","Create sunlight","Turn consumers into producers","Stop energy flow"],"answer":"Return nutrients from dead matter to the ecosystem","hint":"Think about what happens to dead organisms.","why":"Decomposers break down dead material and recycle nutrients into ecosystems."}]
},
"Technology":{
"Beginner":[
{"q":"What is the main job of a computer's CPU?","options":["Process instructions","Print paper","Store electricity","Create Wi-Fi"],"answer":"Process instructions","hint":"It is often compared to the computer's brain.","why":"The CPU executes instructions and performs calculations."},
{"q":"Which is an example of an input device?","options":["Keyboard","Monitor","Speaker","Projector"],"answer":"Keyboard","hint":"An input device sends information into the computer.","why":"A keyboard sends user input into the computer."},
{"q":"What does a password help protect?","options":["Access to an account","Screen brightness","Battery size","Printer paper"],"answer":"Access to an account","hint":"Think cybersecurity.","why":"Passwords are one method for controlling access to accounts and systems."}],
"Intermediate":[
{"q":"In programming, what is a variable?","options":["A named place that stores a value","A computer fan","A type of monitor","A network cable"],"answer":"A named place that stores a value","hint":"Programs need names for information that can change.","why":"Variables associate names with data values used by a program."},
{"q":"What is an algorithm?","options":["A step-by-step method for solving a problem","A physical computer chip","A type of battery","A screen resolution"],"answer":"A step-by-step method for solving a problem","hint":"A recipe is a useful analogy.","why":"An algorithm is an ordered procedure or set of steps for accomplishing a task."},
{"q":"Why is two-factor authentication useful?","options":["It requires a second form of verification","It makes passwords visible","It removes encryption","It doubles internet speed"],"answer":"It requires a second form of verification","hint":"It adds another proof that the user really is the account owner.","why":"Two-factor authentication adds a second verification factor beyond a password."}],
"Advanced":[
{"q":"What does machine learning usually mean?","options":["A system learns patterns from data to make predictions or decisions","A computer repairs its own hardware","A monitor increases resolution automatically","A router creates electricity"],"answer":"A system learns patterns from data to make predictions or decisions","hint":"Think about examples rather than hand-written rules for every case.","why":"Machine learning uses data to learn patterns that can generalize to new inputs."},
{"q":"Why is binary important in digital computers?","options":["Two-state signals are easy for electronic circuits to represent reliably","Computers can only count to two","Binary removes the need for memory","Binary makes electricity unnecessary"],"answer":"Two-state signals are easy for electronic circuits to represent reliably","hint":"Think about on/off electrical states.","why":"Digital circuits can reliably distinguish between two voltage/state ranges, represented as 0 and 1."},
{"q":"What is the purpose of an API?","options":["Provide a defined way for software systems to communicate","Increase monitor brightness","Replace all operating systems","Store electricity"],"answer":"Provide a defined way for software systems to communicate","hint":"It is like a menu of allowed software requests.","why":"An API defines interfaces that let software components request data or actions from one another."}]
},
"Engineering":{
"Beginner":[
{"q":"What is usually the first step in an engineering design process?","options":["Identify the problem","Paint the solution","Buy the most expensive material","Skip testing"],"answer":"Identify the problem","hint":"You need to know what you are trying to solve.","why":"Engineering begins by understanding the need, problem, requirements, and constraints."},
{"q":"Why do engineers build prototypes?","options":["To test ideas","To avoid learning","To guarantee perfection","To remove measurements"],"answer":"To test ideas","hint":"A prototype is not necessarily the final product.","why":"Prototypes let engineers test assumptions and learn before finalizing a design."},
{"q":"Which shape is commonly used in structures because it can be very stable?","options":["Triangle","Random squiggle","Open arc","Loose spiral"],"answer":"Triangle","hint":"Think about many bridges and roof trusses.","why":"Triangles resist shape changes unless side lengths change, which makes them useful in structures."}],
"Intermediate":[
{"q":"A bridge must hold more weight without adding much material. Which idea is most useful?","options":["Use a truss structure","Remove all supports","Make every part flexible","Ignore load paths"],"answer":"Use a truss structure","hint":"Triangles can distribute forces efficiently.","why":"Trusses use interconnected triangles to carry loads efficiently."},
{"q":"What is a design constraint?","options":["A limit or requirement the solution must satisfy","A decoration with no effect","An answer chosen after testing","A random idea"],"answer":"A limit or requirement the solution must satisfy","hint":"Examples include cost, size, safety, or material limits.","why":"Constraints restrict the design space and help define acceptable solutions."},
{"q":"Why do engineers repeat test-and-redesign cycles?","options":["To improve the design using evidence","Because the first design must be copied exactly","To avoid measurements","To make results less reliable"],"answer":"To improve the design using evidence","hint":"Iteration is an important engineering habit.","why":"Testing exposes weaknesses, and redesign uses those observations to improve performance."}],
"Advanced":[
{"q":"What is a safety factor in engineering?","options":["Extra capacity beyond the expected design load","A way to remove testing","A guarantee that failure is impossible","The color of a warning sign"],"answer":"Extra capacity beyond the expected design load","hint":"Engineers account for uncertainty and unexpected conditions.","why":"Safety factors provide margin between expected service loads and failure capacity."},
{"q":"What is the central purpose of a trade-off analysis?","options":["Compare competing benefits and costs among design choices","Find a design with no disadvantages","Avoid choosing requirements","Make every component identical"],"answer":"Compare competing benefits and costs among design choices","hint":"Improving one property may worsen another.","why":"Engineering choices often balance cost, performance, reliability, weight, safety, and other constraints."},
{"q":"Why is redundancy used in critical systems?","options":["To preserve function if one component fails","To reduce all system complexity","To make testing unnecessary","To guarantee zero defects"],"answer":"To preserve function if one component fails","hint":"Think about backup components.","why":"Redundancy provides alternate paths or components when a primary element fails."}]
},
"Arts":{
"Beginner":[
{"q":"What are the three traditional primary colors in painting?","options":["Red, yellow, blue","Green, orange, purple","Black, white, gray","Pink, teal, brown"],"answer":"Red, yellow, blue","hint":"These are the traditional pigment-mixing primaries taught in basic art.","why":"Traditional art education commonly teaches red, yellow, and blue as primary pigment colors."},
{"q":"What does rhythm in music describe?","options":["The pattern of beats in time","Only how loud a sound is","The color of an instrument","The shape of a stage"],"answer":"The pattern of beats in time","hint":"You can clap it.","why":"Rhythm organizes sounds and silences through time."},
{"q":"Which design principle helps make one part stand out?","options":["Emphasis","Camouflage","Silence","Randomness"],"answer":"Emphasis","hint":"Think about where your eyes go first.","why":"Emphasis creates a focal point that attracts attention."}],
"Intermediate":[
{"q":"What is perspective used for in drawing?","options":["Create an illusion of depth","Measure sound","Calculate temperature","Encrypt data"],"answer":"Create an illusion of depth","hint":"Think about objects appearing smaller when farther away.","why":"Perspective uses visual rules to represent three-dimensional depth on a two-dimensional surface."},
{"q":"What does contrast do in visual design?","options":["Creates noticeable differences between elements","Makes every element identical","Removes all focal points","Guarantees symmetry"],"answer":"Creates noticeable differences between elements","hint":"Think light vs dark, large vs small, smooth vs rough.","why":"Contrast emphasizes differences and can improve hierarchy and readability."},
{"q":"In music, what is tempo?","options":["The speed of the beat","The name of the composer","The pitch of one note","The instrument material"],"answer":"The speed of the beat","hint":"A fast song and a slow song differ in this property.","why":"Tempo is the rate or speed of the musical beat."}],
"Advanced":[
{"q":"Why is negative space important in visual design?","options":["It helps organize and separate visual elements","It means the artwork is unfinished","It removes the need for composition","It must always be filled with text"],"answer":"It helps organize and separate visual elements","hint":"Empty areas can affect readability and focus.","why":"Negative space gives elements breathing room and helps shape hierarchy, balance, and focus."},
{"q":"What is visual hierarchy?","options":["Arranging elements so viewers notice them in an intended order","Using only one font size","Removing contrast","Making all elements equally prominent"],"answer":"Arranging elements so viewers notice them in an intended order","hint":"Design can guide the eye from most important to least important.","why":"Visual hierarchy uses size, placement, contrast, spacing, and other cues to guide attention."},
{"q":"What does syncopation do in music?","options":["Places emphasis on unexpected beats or parts of beats","Makes every beat equally strong","Removes rhythm","Changes a song into silence"],"answer":"Places emphasis on unexpected beats or parts of beats","hint":"It creates rhythmic surprise.","why":"Syncopation shifts accents away from expected strong beats, creating rhythmic tension and interest."}]
},
"Math":{
"Beginner":[
{"q":"What is 7 × 8?","options":["56","54","48","64"],"answer":"56","hint":"Think 7 groups of 8.","why":"7 × 8 = 56."},
{"q":"Which fraction is equal to one half?","options":["2/4","1/3","3/4","2/3"],"answer":"2/4","hint":"Multiply numerator and denominator of 1/2 by the same number.","why":"1/2 × 2/2 = 2/4."},
{"q":"A rectangle is 5 cm long and 3 cm wide. What is its area?","options":["15 cm²","16 cm²","8 cm²","10 cm²"],"answer":"15 cm²","hint":"Area of a rectangle uses length and width.","why":"5 × 3 = 15 square centimeters."}],
"Intermediate":[
{"q":"What is 25% of 80?","options":["20","15","25","40"],"answer":"20","hint":"25% is one quarter.","why":"80 ÷ 4 = 20."},
{"q":"Solve: 3x + 5 = 20.","options":["x = 5","x = 4","x = 6","x = 3"],"answer":"x = 5","hint":"Undo addition first, then multiplication.","why":"3x + 5 = 20 → 3x = 15 → x = 5."},
{"q":"A car travels 120 miles in 2 hours. What is its average speed?","options":["60 mph","240 mph","122 mph","30 mph"],"answer":"60 mph","hint":"Average speed = distance ÷ time.","why":"120 ÷ 2 = 60 miles per hour."}],
"Advanced":[
{"q":"A right triangle has legs 6 and 8. What is the hypotenuse?","options":["10","12","14","7"],"answer":"10","hint":"Use the relationship among the three sides of a right triangle.","why":"6² + 8² = 36 + 64 = 100, so the hypotenuse is √100 = 10."},
{"q":"If y = 2x + 3, what is y when x = 4?","options":["11","8","14","5"],"answer":"11","hint":"Substitute 4 for x.","why":"y = 2(4) + 3 = 8 + 3 = 11."},
{"q":"A bag has 3 red and 2 blue marbles. If one marble is chosen at random, what is the probability it is red?","options":["3/5","2/5","1/2","3/2"],"answer":"3/5","hint":"Probability = favorable outcomes ÷ total equally likely outcomes.","why":"There are 3 red marbles out of 5 total, so the probability is 3/5."}]
}}
